### ISSUE TITLE
dep-graph not working?

### ISSUE THREAD

**Issue by jrstrayhorn** [dalemanthei/nx-ng-packagr-demo#1]
Hello @dalemanthei - this is NOT an issue per say but more of a question and I wasn't sure about how to get into contact with you so here goes...

You mention in the readme that the nx commands for dep-graph and/or affected don't work and I was just curious as to why that is.

I'm working on adjusting a project to a similar approach as yours and wanted to understand why those command no longer work.

Thanks for your time!

**Comment by dalemanthei** [comment]
@jrstrayhorn Opening an issue is fine with me.

I think the crux of the problem is an undocumented dependency between the import paths for components and the folder structure in the project.

Here's the dep-graph for the master branch:

![image](https://user-images.githubusercontent.com/6266984/73794363-e65bba80-476d-11ea-93cb-270d8bb8519f.png)

Here's a dep-graph for the `working-dep-graph` branch I just created:

![image](https://user-images.githubusercontent.com/6266984/73794333-d0e69080-476d-11ea-8125-11d0dc15e203.png)

Getting the dep-graph to work is a global change from `@dmv/demo/` to `@dmv/`. There might be a way to structure the folders in the project to something like `../libs/demo/button` etc that could make this work. In our production repo our path was `@vdlx/vdl-angular/..`. I think the hyphenated part of the path `vdl-angular` gave us more troubles since some part of the tooling seemed to want `../libs/vdl/angular/..`.

We just didn't have the luxury of resources to see if we could go down that path. However, now that I have this repo and there's only a single, non-hyphenated element between the npm space and component it could be made to work.

I do have hopes that the nx team's work on this will eventually solve for this. Or at the very least make the path to folder mapping explicit that we can make it work for us.

Hope this helps!

**Comment by dalemanthei** [comment]
@jrstrayhorn Ok, the above got me to thinking... so I made another branch to insert a demo folder and it got the dep-graph working another way but not quite complete.

The branch is `use-demo-folder`

Here's the dep-graph for that branch:

![image](https://user-images.githubusercontent.com/6266984/73795776-16f12380-4771-11ea-8e50-78b68bcd3c42.png)

It's still disconnected between the apps and the components but within the components the graph is ok.

**Comment by jrstrayhorn** [comment]
@dalemanthei - wow! thanks so much for taking a look at this and responding.. 

ah ha!! so adding a root /demo folder under /libs to match tsconfig paths got the dep-graph working? "going to try this in our project here shortly"

I believe this is the scenario we'd want so we can have at least some sort of dep-graph that can show how all the components/libs are connected to one another - this can help with ensuring proper ordering of lib building.

One more questions - do you do any sort of automating to make sure the libs/components are building in the right order?  I'm thinking manually may be the only way but wanted to pick your brain on it.

Thanks again!!

**Comment by dalemanthei** [comment]
Reference the README for the building the library. It probably only works for master but the package.json scripts have the manual sequencing.

**Comment by jrstrayhorn** [comment]
That makes sense!! Thanks so much!! will close this...
